In [1]:
import numpy as np

In [2]:
num = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
num

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [3]:
now = np.mat(num)
now

matrix([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

In [4]:
np.mean(now)  # 对所有元素求均值

3.5

In [5]:
np.mean(now,0)  # 压缩行，对各列求均值

matrix([[2.5, 3.5, 4.5]])

In [6]:
np.mean(now,1)  # 压缩列，对各行求均值

matrix([[2.],
        [3.],
        [4.],
        [5.]])